# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/archimed/21-school/pirs/rpn_calculator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/archimed/21-school/pirs/rpn_calculator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/archimed/21-school/pirs/rpn_calculator/CMakeFiles /home/archimed/21-school/pirs/rpn_calculator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/archimed/21-school/pirs/rpn_calculator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named calc_prod

# Build rule for target.
calc_prod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calc_prod
.PHONY : calc_prod

# fast build rule for target.
calc_prod/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/build
.PHONY : calc_prod/fast

#=============================================================================
# Target rules for targets named calc

# Build rule for target.
calc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calc
.PHONY : calc

# fast build rule for target.
calc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/build
.PHONY : calc/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/format.dir/build.make CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named test_format

# Build rule for target.
test_format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_format
.PHONY : test_format

# fast build rule for target.
test_format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_format.dir/build.make CMakeFiles/test_format.dir/build
.PHONY : test_format/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named leaks

# Build rule for target.
leaks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leaks
.PHONY : leaks

# fast build rule for target.
leaks/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leaks.dir/build.make CMakeFiles/leaks.dir/build
.PHONY : leaks/fast

#=============================================================================
# Target rules for targets named cppcheck

# Build rule for target.
cppcheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cppcheck
.PHONY : cppcheck

# fast build rule for target.
cppcheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppcheck.dir/build.make CMakeFiles/cppcheck.dir/build
.PHONY : cppcheck/fast

#=============================================================================
# Target rules for targets named gcov_report

# Build rule for target.
gcov_report: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gcov_report
.PHONY : gcov_report

# fast build rule for target.
gcov_report/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcov_report.dir/build.make CMakeFiles/gcov_report.dir/build
.PHONY : gcov_report/fast

#=============================================================================
# Target rules for targets named gcov_build

# Build rule for target.
gcov_build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gcov_build
.PHONY : gcov_build

# fast build rule for target.
gcov_build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcov_build.dir/build.make CMakeFiles/gcov_build.dir/build
.PHONY : gcov_build/fast

#=============================================================================
# Target rules for targets named dvi

# Build rule for target.
dvi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dvi
.PHONY : dvi

# fast build rule for target.
dvi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dvi.dir/build.make CMakeFiles/dvi.dir/build
.PHONY : dvi/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named install_target

# Build rule for target.
install_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 install_target
.PHONY : install_target

# fast build rule for target.
install_target/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/install_target.dir/build.make CMakeFiles/install_target.dir/build
.PHONY : install_target/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named calc_prod_autogen

# Build rule for target.
calc_prod_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calc_prod_autogen
.PHONY : calc_prod_autogen

# fast build rule for target.
calc_prod_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod_autogen.dir/build.make CMakeFiles/calc_prod_autogen.dir/build
.PHONY : calc_prod_autogen/fast

#=============================================================================
# Target rules for targets named calc_autogen

# Build rule for target.
calc_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calc_autogen
.PHONY : calc_autogen

# fast build rule for target.
calc_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_autogen.dir/build.make CMakeFiles/calc_autogen.dir/build
.PHONY : calc_autogen/fast

#=============================================================================
# Target rules for targets named test_autogen

# Build rule for target.
test_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_autogen
.PHONY : test_autogen

# fast build rule for target.
test_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_autogen.dir/build.make CMakeFiles/test_autogen.dir/build
.PHONY : test_autogen/fast

calc_autogen/mocs_compilation.o: calc_autogen/mocs_compilation.cpp.o
.PHONY : calc_autogen/mocs_compilation.o

# target to build an object file
calc_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/calc_autogen/mocs_compilation.cpp.o
.PHONY : calc_autogen/mocs_compilation.cpp.o

calc_autogen/mocs_compilation.i: calc_autogen/mocs_compilation.cpp.i
.PHONY : calc_autogen/mocs_compilation.i

# target to preprocess a source file
calc_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/calc_autogen/mocs_compilation.cpp.i
.PHONY : calc_autogen/mocs_compilation.cpp.i

calc_autogen/mocs_compilation.s: calc_autogen/mocs_compilation.cpp.s
.PHONY : calc_autogen/mocs_compilation.s

# target to generate assembly for a file
calc_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/calc_autogen/mocs_compilation.cpp.s
.PHONY : calc_autogen/mocs_compilation.cpp.s

calc_prod_autogen/mocs_compilation.o: calc_prod_autogen/mocs_compilation.cpp.o
.PHONY : calc_prod_autogen/mocs_compilation.o

# target to build an object file
calc_prod_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/calc_prod_autogen/mocs_compilation.cpp.o
.PHONY : calc_prod_autogen/mocs_compilation.cpp.o

calc_prod_autogen/mocs_compilation.i: calc_prod_autogen/mocs_compilation.cpp.i
.PHONY : calc_prod_autogen/mocs_compilation.i

# target to preprocess a source file
calc_prod_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/calc_prod_autogen/mocs_compilation.cpp.i
.PHONY : calc_prod_autogen/mocs_compilation.cpp.i

calc_prod_autogen/mocs_compilation.s: calc_prod_autogen/mocs_compilation.cpp.s
.PHONY : calc_prod_autogen/mocs_compilation.s

# target to generate assembly for a file
calc_prod_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/calc_prod_autogen/mocs_compilation.cpp.s
.PHONY : calc_prod_autogen/mocs_compilation.cpp.s

dialog.o: dialog.cpp.o
.PHONY : dialog.o

# target to build an object file
dialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/dialog.cpp.o
.PHONY : dialog.cpp.o

dialog.i: dialog.cpp.i
.PHONY : dialog.i

# target to preprocess a source file
dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/dialog.cpp.i
.PHONY : dialog.cpp.i

dialog.s: dialog.cpp.s
.PHONY : dialog.s

# target to generate assembly for a file
dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/dialog.cpp.s
.PHONY : dialog.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/main.cpp.s
.PHONY : main.cpp.s

main_test.o: main_test.c.o
.PHONY : main_test.o

# target to build an object file
main_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/main_test.c.o
.PHONY : main_test.c.o

main_test.i: main_test.c.i
.PHONY : main_test.i

# target to preprocess a source file
main_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/main_test.c.i
.PHONY : main_test.c.i

main_test.s: main_test.c.s
.PHONY : main_test.s

# target to generate assembly for a file
main_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/main_test.c.s
.PHONY : main_test.c.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

src/polish.o: src/polish.c.o
.PHONY : src/polish.o

# target to build an object file
src/polish.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/src/polish.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/polish.c.o
.PHONY : src/polish.c.o

src/polish.i: src/polish.c.i
.PHONY : src/polish.i

# target to preprocess a source file
src/polish.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/src/polish.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/polish.c.i
.PHONY : src/polish.c.i

src/polish.s: src/polish.c.s
.PHONY : src/polish.s

# target to generate assembly for a file
src/polish.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/src/polish.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/polish.c.s
.PHONY : src/polish.c.s

src/qcustomplot.o: src/qcustomplot.cpp.o
.PHONY : src/qcustomplot.o

# target to build an object file
src/qcustomplot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/src/qcustomplot.cpp.o
.PHONY : src/qcustomplot.cpp.o

src/qcustomplot.i: src/qcustomplot.cpp.i
.PHONY : src/qcustomplot.i

# target to preprocess a source file
src/qcustomplot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/src/qcustomplot.cpp.i
.PHONY : src/qcustomplot.cpp.i

src/qcustomplot.s: src/qcustomplot.cpp.s
.PHONY : src/qcustomplot.s

# target to generate assembly for a file
src/qcustomplot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc_prod.dir/build.make CMakeFiles/calc_prod.dir/src/qcustomplot.cpp.s
.PHONY : src/qcustomplot.cpp.s

test_autogen/mocs_compilation.o: test_autogen/mocs_compilation.cpp.o
.PHONY : test_autogen/mocs_compilation.o

# target to build an object file
test_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test_autogen/mocs_compilation.cpp.o
.PHONY : test_autogen/mocs_compilation.cpp.o

test_autogen/mocs_compilation.i: test_autogen/mocs_compilation.cpp.i
.PHONY : test_autogen/mocs_compilation.i

# target to preprocess a source file
test_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test_autogen/mocs_compilation.cpp.i
.PHONY : test_autogen/mocs_compilation.cpp.i

test_autogen/mocs_compilation.s: test_autogen/mocs_compilation.cpp.s
.PHONY : test_autogen/mocs_compilation.s

# target to generate assembly for a file
test_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test_autogen/mocs_compilation.cpp.s
.PHONY : test_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... calc_autogen"
	@echo "... calc_prod_autogen"
	@echo "... clean-all"
	@echo "... cppcheck"
	@echo "... dist"
	@echo "... dvi"
	@echo "... format"
	@echo "... gcov_build"
	@echo "... gcov_report"
	@echo "... install_target"
	@echo "... leaks"
	@echo "... run_tests"
	@echo "... test_autogen"
	@echo "... test_format"
	@echo "... uninstall"
	@echo "... calc"
	@echo "... calc_prod"
	@echo "... test"
	@echo "... calc_autogen/mocs_compilation.o"
	@echo "... calc_autogen/mocs_compilation.i"
	@echo "... calc_autogen/mocs_compilation.s"
	@echo "... calc_prod_autogen/mocs_compilation.o"
	@echo "... calc_prod_autogen/mocs_compilation.i"
	@echo "... calc_prod_autogen/mocs_compilation.s"
	@echo "... dialog.o"
	@echo "... dialog.i"
	@echo "... dialog.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... main_test.o"
	@echo "... main_test.i"
	@echo "... main_test.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... src/polish.o"
	@echo "... src/polish.i"
	@echo "... src/polish.s"
	@echo "... src/qcustomplot.o"
	@echo "... src/qcustomplot.i"
	@echo "... src/qcustomplot.s"
	@echo "... test_autogen/mocs_compilation.o"
	@echo "... test_autogen/mocs_compilation.i"
	@echo "... test_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

